server:
    port: 8080
spring:
    application:
        name: customer-service
    datasource:
        url: jdbc:h2:mem:customers-db
    cloud:
        discovery:
            enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"