
server:
    port: 8081
spring:
    application:
        name: inventory-service
    datasource:
        url: jdbc:h2:mem:inventory-db
    cloud:
        discovery:
            enabled: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"